import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import {
  ApolloClient,
  createHttpLink,
  InMemoryCache,
  gql,
} from '@apollo/client';
import { setContext } from '@apollo/client/link/context';

export default function Home({ widgets }) {
  console.log('widgets', widgets);
  return (
    <div className={styles.container}>
      <Head>
        <title>Headless Widgets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <div className={styles.grid}>
            {widgets.map((widget) => {
              function returnHTML(widget) {
                return { __html: widget.html };
              }
              return (
                <>
                  <h3>{widget.name}</h3>
                  <div dangerouslySetInnerHTML={returnHTML(widget)}></div>
                  <p>{widget.html}</p>
                </>
              );
            })}
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps() {
  const httpLink = createHttpLink({
    uri: 'https://store-29iql3rwa6.mybigcommerce.com/graphql',
  });

  const authLink = setContext((_, { headers }) => {
    // get the authentication token from local storage if it exists
    // return the headers to the context so httpLink can read them
    return {
      headers: {
        ...headers,
        authorization: `Bearer ${process.env.REACT_APP_BIGCOMMERCE_TOKEN}`,
      },
    };
  });
  const client = new ApolloClient({
    link: authLink.concat(httpLink),
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query fetchWidgets {
        site {
          content {
            renderedRegionsByPageType(pageType: HOME) {
              regions {
                name
                html
              }
            }
          }
        }
      }
    `,
  });
  return {
    props: {
      widgets: data.site.content.renderedRegionsByPageType.regions,
    },
  };
}
